# add -Wall to try to catch everything we can.
#ccflags-y += -I$(srctree)/techpack/audio/include
#ccflags-y += -I$(srctree)/techpack/audio/include/uapi/

ifdef CONFIG_SND_SOC_AW87XXX
AW87XXX_OBJS += aw87xxx.o
AW87XXX_OBJS += aw87xxx_device.o
AW87XXX_OBJS += aw87xxx_monitor.o
AW87XXX_OBJS += aw87xxx_bin_parse.o
AW87XXX_OBJS += aw87xxx_dsp.o
AW87XXX_OBJS += aw87xxx_acf_bin.o
endif

obj-$(CONFIG_SND_SOC_AW87XXX) += $(AW87XXX_OBJS)
