# add -Wall to try to catch everything we can.

ifneq ($(filter m y,$(CONFIG_MMI_BQ25980_BULK_READ)),)
        ccflags-y += -DCONFIG_MMI_BQ25980_BULK_READ
endif

obj-$(CONFIG_BQ25980_MMI_IIO_CHARGER) += bq25980_mmi_iio.o
