# add -Wall to try to catch everything we can.
ccflags-y += -DCONFIG_AW882XX_CODEC -DCONFIG_AW882XX_DSP

ifeq ($(CONFIG_AW882XX_STEREO_SMARTPA), y)
    ccflags-y += -DCONFIG_AW882XX_STEREO_SMARTPA
    ccflags-y += -DAW_SPIN_ENABLE
endif

ifeq ($(CONFIG_AW882XX_PARAMS_FROM_BIN), y)
    ccflags-y += -DCONFIG_AW882XX_ALGO_BIN_PARAMS
endif

aw882xx_acf-objs += aw882xx.o
aw882xx_acf-objs += aw_bin_parse.o
aw882xx_acf-objs += aw_calib.o
aw882xx_acf-objs += aw_device.o
aw882xx_acf-objs += aw_dsp.o
aw882xx_acf-objs += aw_init.o
aw882xx_acf-objs += aw_monitor.o

obj-$(CONFIG_SND_SOC_AW882XX) += aw882xx_acf.o
